
[tools]
# fd is a dependency of telescope and fzf-lua
"ubi:sharkdp/fd" = "10.3.0"
"ubi:junegunn/fzf" = "0.65.2"
"ubi:EmmyLuaLs/emmylua-analyzer-rust" = { version = "0.13.0", exe = "emmylua_ls", matching_regex = "^emmylua_ls" }
lua = "5.1"
# ripgrep is a dependency of telescope and fzf-lua
"ubi:BurntSushi/ripgrep" = { version = "14.1.1", exe = "rg" }
"ubi:JohnnyMorganz/stylua" = "2.1.0"
