minimumReleaseAge: 4320 # 3 days, https://pnpm.io/settings/dependency-resolution#minimumreleaseage
packages:
  - integration-tests/
allowBuilds:
  cypress: true
  esbuild: true
saveExact: true

# https://pnpm.io/pnpm-workspace_yaml
