# https://yazi-rs.github.io/docs/configuration/overview
# https://yazi-rs.github.io/docs/configuration/keymap
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# NOTE: this is also documented in yazi-keymappings.md as a user facing example
# send an event with no data
[[mgr.prepend_keymap]]
on = "<C-p>"
run = """shell 'ya pub-to 0 my-message-no-data'"""

# NOTE: this is also documented in yazi-keymappings.md as a user facing example
# send an event that also has json data
[[mgr.prepend_keymap]]
on = "<C-h>"
run = """shell --
json=$(printf '{"selected_file": "%s"}' "$0")
ya pub-to 0 my-change-working-directory-command --json "$json"
"""

[[mgr.prepend_keymap]]
on = "i"
run = """quit"""

[[mgr.prepend_keymap]]
on = "I"
run = """shell "ya pub-to 0 nvim-cycle-buffer""""
