# https://yazi-rs.github.io/docs/configuration/overview
# https://yazi-rs.github.io/docs/configuration/keymap
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

# NOTE: this is also documented in yazi-keymappings.md as a user facing example
# send an event with no data
[[manager.prepend_keymap]]
on = "<C-p>"
run = """shell 'ya pub-to 0 MyMessageNoData' --confirm"""

# NOTE: this is also documented in yazi-keymappings.md as a user facing example
# send an event that also has json data
[[manager.prepend_keymap]]
on = "<C-h>"
run = """shell "ya pub-to 0 MyMessageWithData --json '{\\"somedata\\": 123}'" --confirm"""
