# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Commit message lint
permissions:
  contents: read

on:
  pull_request: ~

jobs:
  commitlint:
    runs-on: ubuntu-24.04
    name: commitlint
    steps:
      - name: Compute fetch depth
        id: depth
        shell: bash
        env:
          # `+ 1` to include the PR base commit so commitlint can determine the range
          COMMITS: ${{ github.event.pull_request.commits }}
        run: |
          echo "Linting $COMMITS commits"
          echo "value=$((COMMITS + 1))" >> "$GITHUB_OUTPUT"

      - name: Checkout PR
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: ${{ steps.depth.outputs.value }}
          persist-credentials: false

      - uses: wagoid/commitlint-github-action@b948419dd99f3fd78a6548d48f94e3df7f6bf3ed # v6.2.1
