name: Linkspector
on: [pull_request]
permissions:
  pull-requests: write
  contents: read
jobs:
  check-links:
    uses: mikavilpas/dotfiles/.github/workflows/linkspector.yml@46bc75f9510634a4ed3470381dd2c75d6088f893 # main
    secrets: inherit
