name: Linting
permissions:
  contents: read
on: [push, pull_request]

jobs:
  selene:
    name: selene
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: NTBBloodbath/selene-action@23ef05dd5c4d687f4d3c939f76a1c342baf454aa # v1.0.0
        with:
          # Github secret token
          token: ${{ secrets.GITHUB_TOKEN }}
          # selene arguments, should be the same as in ../../mise.toml
          args:
            --display-style=quiet ./lua/ ./spec/
            ./integration-tests/test-environment/config-modifications
          # selene version
          # renovate: datasource=github-releases depName=Kampfkarren/selene
          version: 0.31.0

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/rvben/rumdl?tab=readme-ov-file#github-actions
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - uses: rvben/rumdl@50035a41350da1b037486cfa1e9ade36dcb00801 # v0

  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: actionlint
        uses: raven-actions/actionlint@3d39aea434753780c3b3d4a1a31c854b4dbf49d7 # v2.2.0

  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          # https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time
          run_install: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install
        env:
          CYPRESS_INSTALL_BINARY: "0"
      - run: pnpm run lint
