name: Linting
permissions:
  contents: read
on: [push, pull_request]

jobs:
  selene:
    name: selene
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: NTBBloodbath/selene-action@23ef05dd5c4d687f4d3c939f76a1c342baf454aa # v1.0.0
        with:
          # Github secret token
          token: ${{ secrets.GITHUB_TOKEN }}
          # selene arguments, should be the same as in ../../mise.toml
          args:
            --display-style=quiet ./lua/ ./spec/
            ./integration-tests/test-environment/config-modifications
          # selene version
          # renovate: datasource=github-releases depName=Kampfkarren/selene
          version: 0.30.1

  markdownlint:
    name: markdownlint
    runs-on: ubuntu-24.04
    steps:
      # https://github.com/rvben/rumdl?tab=readme-ov-file#github-actions
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: rvben/rumdl@8e22c9b16f49c7209355106f731500cc1aacef20 # v0

  actionlint:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: actionlint
        uses: raven-actions/actionlint@205b530c5d9fa8f44ae9ed59f341a0db994aa6f8 # v2.1.2

  lint:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: pnpm/action-setup@fc06bc1257f339d1d5d8b3a19a8cae5388b55320 # v5.0.0
        with:
          # https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time
          run_install: false
      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6.3.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install
      - run: pnpm run lint
