# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: Style checking

on:
  pull_request: ~
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  oxfmt:
    runs-on: ubuntu-24.04
    name: oxfmt
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9
        with:
          # https://github.com/pnpm/action-setup?tab=readme-ov-file#use-cache-to-reduce-installation-time
          run_install: false
      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version-file: .nvmrc
          cache: "pnpm"
      - run: pnpm install --filter @yazi.nvim/plugin
      - run: pnpm oxfmt --check

  stylua:
    name: stylua
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: JohnnyMorganz/stylua-action@76fd70c03e6340ceaf673366712db9b20560b402 # v5.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          # renovate: datasource=github-releases depName=JohnnyMorganz/StyLua
          version: v2.5.2
          # CLI arguments
          args: --color always --check --allow-hidden .
