---
name: Type check
on:
  pull_request: ~
  push: ~

jobs:
  build:
    name: Type check
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: stevearc/nvim-typecheck-action@v2
        name: Type check lua/
        with:
          path: lua
          level: Information
          libraries:
            # space separated
            https://github.com/nvim-lua/plenary.nvim

      - uses: stevearc/nvim-typecheck-action@v2
        with:
          name: Type check tests/
          path: tests/
          level: Information
          libraries:
            # space separated
            https://github.com/nvim-lua/plenary.nvim
