---
name: Type check
on:
  pull_request: ~
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    name: Type check
    runs-on: ubuntu-24.04
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: stevearc/nvim-typecheck-action@a2c7bff1c2f1d8489106271c8f89183628d41655 # v2
        with:
          path: lua
          level: Information
          libraries:
            # space separated
            https://github.com/nvim-lua/plenary.nvim
            https://github.com/folke/snacks.nvim
